name: rick_and_morty_api
description: Rick And Morty API
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  test: ^1.24.4
  very_good_analysis: 5.0.0+1
