name: rick_and_morty_api
description: Rick And Morty API
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  http: ^0.13.5
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  test: ^1.23.1
  very_good_analysis: 4.0.0+1
